---
name: Checks

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake8
        run: flake8 .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint]

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: orders_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        ports:
          - 5432/tcp
    steps:
    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test
      run: python -m unittest
      env:
        POSTGRES_HOST: localhost

